server:
  port: 8200
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nettyboy/spring-cloud-examples.git
          username: nettyboy
          password: ningquan168
  #rbbitmq配置
  rabbitmq:
    host: localhost
    port: 5762
    username: admin
    password: admin123
    
#关闭安全验证 spring 1.5.X
management:
  security:
    enabled: false
    
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/ #注册中erueka-server
      
  instance:
    appname: microservice-config-server