server:
  port: 8200
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nettyboy/spring-cloud-examples.git
          username: nettyboy
          password: xxxx
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/ #注册中erueka-server
      
  instance:
    appname: microservice-config-server