server:
  port: 8100
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nettyboy/spring-cloud-examples/microservice-cloud-config/
#          search-paths:
#          - microservice-cloud-config
          username: nettyboy
          password: ningquan168
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/ #注册中erueka-server
      
  instance:
    appname: microservice-config-server