server:
  port: 8100
  
#设置spring-config-server安全认证用户名和密码
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123
    
spring:
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nettyboy/spring-cloud-examples/
              #https://github.com/nettyboy/{application} 这里的application 指的是repo，如果每个项目一个repo配置可以在这里指定
          search-paths: '{application}' #根据应用不同可以根据应用名称指定占位符
          username: nettyboy
          password: ningquan168
          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7100/eureka/ #注册中erueka-server
      
  instance:
    appname: microservice-config-server